### ISSUE TITLE
List column "bouncing" up/down?

### ISSUE THREAD

**Issue by LorenAmelang** [crshd/startpage.rwrt#4]
I'm not sure how I accidentally trigger it, but I often see (any) one of my link columns repeatedly expanding and contracting over and over. It will keep bouncing as long as the cursor is below the column heading but within the area where the link items drop down. Mouse up to the header and it will stay down. Mouse out of the column and it will bounce several more times before closing upward. 

To trigger it intentionally, put your cursor in the blank space above a column header and drag rapidly down across the header into the link item space. Or, with a column properly expanded, mouse out of the column and back in before it finishes collapsing upward. Yes, I know, "just don't do that!" But I do it unconsciously several times a day...  

Just installed your latest version, and it maybe seems less likely to do this than the 2012 version I had, but can easily be forced to. I haven't spotted what I could play with to tame it - if a column has dropped down and the cursor is still over its expanded area, it should stay down even if the cursor wasn't over the header long enough for it to register properly. Thoughts?

**Comment by crshd** [comment]
It's a known problem. Most likely due to the trigger area moving in and out from under the pointer, creating a trigger "loop".

This should be fixable, unfortunately I myself am not quite sure how to. It probably needs a good bit of rewriting.

**Comment by pete1450** [comment]
Created [pull request](https://github.com/crshd/startpage.rwrt/pull/11) for this isue

**Comment by cbrst** [comment]
Derp. That was easy.

**Comment by pete1450** [comment]
I had to look around for it but yeah; I was surprised when i found that was all it took.

**Comment by LorenAmelang** [comment]
Thanks so much! Seems totally fixed, I can't fool it any more. I suspected there was a simple fix, but it was beyond my experience.
